import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'
import axios from 'axios'
import { Cheerio } from 'cheerio'




export default function Home() {

  const [page, setPage] = useState({
    url: "",
    html: null
  })

  const setUrl = (e) => {
    const value = e.target.value;
    setPage({...page, url: value})
  }

  async function getHTMLFromLink() {

    const response = await fetch("/api/webcrawler?link=" + page.url)
    const content = await response.json()
    return content
  }

  const setHTMLDisplay = async (e) => {
    setPage({...page, html: await getHTMLFromLink()})
  }

  function filterLongDomains(domains) {
    const filtered = domains.filter(domain => domain.length <= 20);
    return filtered;
  }

  function filterDuplicateDomains(domains) {
    const filtered = domains.filter((domain, index) => domains.indexOf(domain) === index);
    return filtered;
  }

  const extractLinks = (html) => {
    const regex = /(?:https?|ftp):\/\/(?:www\.)?([^/]+)\//gi;
    let domains = html.match(regex).map(url => url.replace(regex, '$1'));
    domains = filterLongDomains(domains);
    domains = filterDuplicateDomains(domains);
    return domains;
  }

  return (
    <>
      <Head>
        <title>Countleaf 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>CountLeaf 2.0</h1>
        <div>
          <input placeholder="https://site.com" value={page.url} onChange={setUrl}></input>
          <button className={styles.enterbutton} onClick={setHTMLDisplay}>Enter</button>
        </div>
        <div>{}</div>
        <div className={styles.container}>
          { page.html ? extractLinks(page.html).map( (ele, id) => {
            return <li key={id}>({id}) <a href={"https://" + ele}>{ele}</a></li>
          }) : "" }
        </div>

      </main>
    </>
  )
}
